DROP DATABASE aula_add;
CREATE DATABASE aula_add;
USE aula_add;
CREATE TABLE usuarios(
id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
nome VARCHAR(60) NOT NULL,
email VARCHAR(60) NOT NULL,
senha VARCHAR(60) NOT NULL
);